### PR TITLE
Filepaths

### PR DESCRIPTION
**Pull request by davidanthoff**
First needs a newer version of FilePaths tagged.

### CODE REVIEW

**Comment by vtjnash** [comment]
Will it continue to be possible to not load `FilePaths.jl`, or should I just fork this repo?

**Comment by davidanthoff** [comment]
Is there a problem with FilePaths.jl?

**Comment by vtjnash** [comment]
Just adds unwanted complexity but doesn't solve any problems for me.

**Comment by davidanthoff** [comment]
Well, it does make some of the scenarios I'm working on easier, so I do want to add this. I think FilePaths.jl is a harmless small package, so hopefully the sheer existence of that doesn't require a fork.

If you still need some of the stuff in contrib, I'd be happy to keep that around. I just thought you had moved that into URIParser.jl.

**Comment by davidanthoff** [comment]
Oh, and one more thing: if there _is_ actually any problem with FilePaths.jl (breaks something, doesn't install, anything), please let me know, because then we could certainly reconsider the decision to take a dependency on it.

**Pull request merged**
